### ISSUE TITLE
README update -- Cuis

### ISSUE THREAD

**Issue by hhzl** [mumez/FileMan#1]
The README.md file needs to mention a fourth Smalltalk dialect which is supported -- Cuis.

https://github.com/mumez/Cuis-Smalltalk-FileMan

And what about Visual Works -- is the code available?

**Comment by mumez** [comment]
Thank for the notification. Now I've updated README.
https://github.com/mumez/FileMan/commit/d68d2826ce0b541d366c00387a933723eef20d8c

**Comment by hhzl** [comment]
Thank you for the update and the reference to the VW code.
